[package]
authors = ["Wilfred Hughes"]
name = "userinfo"
version = "0.1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["winuser", "winbase", "lmcons"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.20"
